"""
evidence.py — the bundle, re-derived from the artefacts.

"The evidence bundle must be generated by the implementation. Hardcoded
evidence will not be accepted."

This module runs LAST, in its own process, and it is deliberately amnesiac. It
holds no reference to the trainer, the loader or the run that produced the
artefacts. Its only inputs are files:

    submission_artifacts/run.log
    submission_artifacts/manifests/*.json
    submission_artifacts/ledgers/*.jsonl
    submission_artifacts/checkpoints/*.json
    submission_artifacts/performance.json
    tokenizer/tokenizer.json  and  work/shards/*        (the sealed inputs)

Each requirement is recomputed from those files. Nothing is copied from a
boolean the run happened to leave lying around: the tokenizer hash is
recomputed from the tokenizer file and compared against what the manifests
recorded; the firewall result comes from walking every consume event and
intersecting shard ids with the never-train registry; packing correctness is
checked by REBUILDING windows from ledger coordinates and re-testing the mask
invariants on the rebuilt arrays.

If a claim cannot be reconstructed from the bundle, this module reports FAIL
for it. That is the intended behaviour: an unverifiable claim is not evidence.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List

from . import audit as AU
from . import catalog as CATALOG
from . import config as C
from . import mixture as MIX
from . import packing as PK
from . import plan
from . import tokenizer as TOK
from .dataloader import rebuild_sequences_from_ledger
from .ledger import open_ledgers
from .runlog import read_markers


@dataclass
class Requirement:
    key: str
    title: str
    result: str                       # PASS | FAIL
    evidence: List[str] = field(default_factory=list)
    detail: Dict[str, Any] = field(default_factory=dict)
    check: str = ""

    def as_dict(self) -> dict:
        return dict(requirement=self.title, key=self.key, result=self.result,
                    how_checked=self.check, evidence=self.evidence,
                    detail=self.detail)


class EvidenceBuilder:
    def __init__(self, artifacts: Path, profile_name: str = C.DEFAULT_PROFILE):
        self.art = Path(artifacts)
        self.profile_name = profile_name
        self.profile = C.PROFILES[profile_name]
        self.rows: List[Requirement] = []

        # Sealed inputs, re-read from disk.
        self.tokenizer = TOK.load()
        self.cat = CATALOG.build_catalog(log=None)
        seqs_per_step = (self.profile["n_ranks"] * self.profile["microbatch"]
                         * self.profile["grad_accum"])
        self.timeline = MIX.compile_timeline(
            self.cat, self.profile["total_steps"], seqs_per_step,
            self.profile["seq_len"])

        self.main = open_ledgers(self.art / "ledgers", C.RUN_ID, C.MAIN_BRANCH)
        self.fork = open_ledgers(self.art / "ledgers", C.RUN_ID, C.FORK_BRANCH)
        self.markers = read_markers(self.art / "run.log")
        self.manifest_index = self._read_json(self.art / "manifests" / "_index.json")
        self.registry_dump = self._read_json(self.art / "manifests" / "_eval_registry.json")
        self.performance = self._read_json(self.art / "performance.json")

    @staticmethod
    def _read_json(path: Path) -> dict:
        if not Path(path).exists():
            return {}
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)

    def add(self, key: str, title: str, ok: bool, check: str,
            evidence: List[str], **detail) -> Requirement:
        r = Requirement(key=key, title=title, result="PASS" if ok else "FAIL",
                        evidence=evidence, detail=detail, check=check)
        self.rows.append(r)
        return r

    # ------------------------------------------------------------------
    # 1. Tokenizer integrity
    # ------------------------------------------------------------------
    def check_tokenizer(self) -> None:
        spec_path = C.TOKENIZER_PATH
        with open(spec_path, "r", encoding="utf-8") as fh:
            spec = json.load(fh)
        recomputed = TOK.tokenizer_hash(spec)

        manifests = sorted((self.art / "manifests").glob("shard-*.json"))
        mismatched = []
        for p in manifests:
            with open(p, "r", encoding="utf-8") as fh:
                man = json.load(fh)
            if man.get("tokenizer_hash") != recomputed:
                mismatched.append(man.get("shard_id"))

        index_ok = self.manifest_index.get("tokenizer_hash") == recomputed
        # Round-trip on real multi-byte text: the tokenizer must be lossless or
        # the token ids in the shards do not mean what the manifests claim.
        probe = "मानसून monsoon calc(expr=\"3*45\") தமிழ்"
        round_trip = self.tokenizer.decode(self.tokenizer.encode(probe)) == probe

        ok = not mismatched and index_ok and round_trip and bool(manifests)
        self.add(
            "tokenizer_integrity", "Tokenizer integrity", ok,
            "recomputed sha256 of tokenizer.json and compared against the "
            "tokenizer_hash recorded in every shard manifest; verified a "
            "multi-byte round trip",
            ["manifests/_index.json", "manifests/shard-*.json", "tokenizer/tokenizer.json"],
            recomputed_tokenizer_hash=recomputed,
            manifest_index_hash=self.manifest_index.get("tokenizer_hash"),
            n_manifests_checked=len(manifests),
            n_mismatched=len(mismatched), mismatched_shards=mismatched,
            vocab_size=self.tokenizer.vocab_size,
            multibyte_round_trip=round_trip)

    # ------------------------------------------------------------------
    # 2. Evaluation firewall
    # ------------------------------------------------------------------
    def check_firewall(self) -> None:
        sweep = AU.firewall_sweep(self.main.consumption, self.cat.registry, self.cat)
        fork_sweep = AU.firewall_sweep(self.fork.consumption, self.cat.registry, self.cat)

        blocked = self.manifest_index.get("blocked", [])
        reasons: Dict[str, List[str]] = {}
        for d in self.manifest_index.get("decisions", []):
            if not d["admitted"]:
                for r in d["reasons"]:
                    reasons.setdefault(r, []).append(d["shard_id"])

        contaminated = [d["shard_id"] for d in self.manifest_index.get("decisions", [])
                        if "eval_overlap" in d.get("reasons", [])]
        never_train_blocked = [d["shard_id"] for d in self.manifest_index.get("decisions", [])
                               if "eval_registry_never_train" in d.get("reasons", [])]

        ok = (sweep["ok"] and fork_sweep["ok"] and bool(blocked)
              and bool(contaminated) and bool(never_train_blocked))
        self.add(
            "evaluation_firewall", "Evaluation firewall", ok,
            "walked every consume event on both branches, collected the shard "
            "ids that actually entered a gradient-bearing batch, and "
            "intersected them with the never-train registry; confirmed the "
            "gate blocked both a registered test shard and a training shard "
            "that shares an n-gram with a benchmark item",
            ["ledgers/consumption_*.jsonl", "manifests/_index.json",
             "manifests/_eval_registry.json"],
            never_train_shards_consumed=sweep["never_train_shards_consumed"],
            non_training_split_shards_consumed=sweep["non_training_split_shards_consumed"],
            blocked_shards_consumed=sweep["blocked_shards_consumed"],
            fork_branch_clean=fork_sweep["ok"],
            n_blocked_shards=len(blocked),
            block_reasons={k: v for k, v in sorted(reasons.items())},
            contamination_blocked=contaminated,
            never_train_blocked=never_train_blocked,
            n_registry_entries=self.registry_dump.get("n_entries"),
            n_contamination_fingerprints=self.registry_dump.get("n_fingerprints"),
            n_distinct_shards_consumed=sweep["n_distinct_shards_consumed"])

    # ------------------------------------------------------------------
    # 3. Packing correctness
    # ------------------------------------------------------------------
    def check_packing(self) -> None:
        """Rebuild windows from ledger coordinates and re-test the invariants.

        Not "did the run say the masks were fine" -- the arrays are rebuilt and
        the four rules are re-checked on the rebuilt arrays.
        """
        seq_len = self.profile["seq_len"]
        events = self.main.consumption.events("consume")
        checked = 0
        violations: List[dict] = []
        util_num = util_den = 0
        loss_tokens = 0
        by_policy: Dict[str, dict] = {}

        for ev in events:
            rebuilt = rebuild_sequences_from_ledger(self.cat, ev, seq_len)
            for rec, s in zip(ev["sequences"], rebuilt):
                checked += 1
                util_num += s.n_real_tokens
                util_den += s.seq_len
                loss_tokens += s.n_loss_tokens
                b = by_policy.setdefault(s.policy, dict(
                    n=0, real=0, positions=0, loss=0, truncated=0,
                    boundary=0, loss_across_boundary=0))
                b["n"] += 1
                b["real"] += s.n_real_tokens
                b["positions"] += s.seq_len
                b["loss"] += s.n_loss_tokens
                b["truncated"] += s.n_truncated
                b["boundary"] += s.boundary_crossings
                b["loss_across_boundary"] += s.loss_across_boundary

                isolating = s.policy in PK.ISOLATING_POLICIES

                # (a) labels agree with the next input wherever loss is taken
                for i in range(s.seq_len - 1):
                    if s.loss_mask[i] and s.labels[i] != s.input_ids[i + 1]:
                        violations.append(dict(step=ev["global_step"], rule="label_shift",
                                               policy=s.policy, position=i))
                        break
                # (b) padding never carries loss
                if any(s.loss_mask[i] and s.segment_ids[i] == 0
                       for i in range(s.seq_len)):
                    violations.append(dict(step=ev["global_step"], rule="loss_on_padding",
                                           policy=s.policy))
                # (c) isolating policies take no loss across a sample boundary
                if isolating and s.loss_across_boundary:
                    violations.append(dict(step=ev["global_step"],
                                           rule="loss_across_isolation_boundary",
                                           policy=s.policy,
                                           count=s.loss_across_boundary))
                # (d) isolating policies restart position ids per segment
                if isolating:
                    seen: Dict[int, int] = {}
                    for i in range(s.seq_len):
                        sid = s.segment_ids[i]
                        if sid == 0:
                            continue
                        want = seen.get(sid, 0)
                        if s.position_ids[i] != want:
                            violations.append(dict(step=ev["global_step"],
                                                   rule="position_id_restart",
                                                   policy=s.policy, position=i))
                            break
                        seen[sid] = want + 1
                # (e) context-only roles never carry loss: re-derived from the
                #     shard span index, independent of what the run recorded
                if s.loss_mask_hash() != rec["loss_mask_hash"]:
                    violations.append(dict(step=ev["global_step"],
                                           rule="loss_mask_hash_mismatch",
                                           policy=s.policy))

        for p, b in by_policy.items():
            b["mean_utilization"] = round(b["real"] / max(1, b["positions"]), 6)
            b["loss_density"] = round(b["loss"] / max(1, b["positions"]), 6)

        ok = checked > 0 and not violations
        self.add(
            "packing_correctness", "Packing correctness", ok,
            "rebuilt every packed window from its ledger coordinates and "
            "re-tested five invariants on the rebuilt arrays: label shift, no "
            "loss on padding, no loss across an isolation boundary, position "
            "ids restarting per segment, and loss-mask hash equality",
            ["ledgers/consumption_main.jsonl", "manifests/shard-*.json"],
            n_sequences_rebuilt=checked,
            n_violations=len(violations), violations=violations[:10],
            overall_packing_utilization=round(util_num / max(1, util_den), 6),
            total_loss_bearing_tokens=loss_tokens,
            by_policy={k: by_policy[k] for k in sorted(by_policy)},
            policies_exercised=sorted(by_policy))

    # ------------------------------------------------------------------
    # 4. Mixture compliance
    # ------------------------------------------------------------------
    def check_mixture(self) -> None:
        comp = AU.mixture_compliance(self.main.consumption, self.timeline)
        floor = AU.floor_compliance(self.main.consumption)
        reserve = AU.anneal_reserve_compliance(self.main.consumption, self.timeline)

        stages_seen = sorted({e["curriculum_stage"]
                              for e in self.main.consumption.events("optimizer_step")})
        tol = 0.02
        ok = (comp["max_abs_unexplained_drift"] <= tol and floor["ok"]
              and reserve["ok"] and len(stages_seen) == len(plan.STAGE_NAMES))

        self.add(
            "mixture_compliance", "Mixture compliance, floors and curriculum", ok,
            "recomputed realised lane shares from the consumption ledger and "
            "compared them against the quotas the timeline compiler produced "
            "from the Session-5 plan, requiring every deviation to be "
            "attributable to a logged scarcity substitution; re-checked the "
            "protected floor in every single batch rather than on average; "
            "verified anneal-reserved shards were untouched before S4",
            ["ledgers/consumption_main.jsonl", "manifests/_index.json"],
            max_abs_unexplained_drift=comp["max_abs_unexplained_drift"],
            max_abs_drift_vs_planned=comp["max_abs_drift_vs_planned"],
            n_substitution_events=comp["n_substitution_events"],
            total_sequences_substituted=comp["total_sequences_substituted"],
            tolerance=tol,
            floor_ok=floor["ok"], floor_pct=floor["floor_pct"],
            floor_violations=floor["n_violations"],
            min_floor_share=floor["min_delivered_share"],
            mean_floor_share=floor["mean_delivered_share"],
            anneal_reserve_ok=reserve["ok"],
            reserved_shards=reserve.get("reserved_shards", []),
            reserved_leaked=reserve.get("leaked_shards", []),
            stages_executed=stages_seen,
            lanes=comp["lanes"])

    # ------------------------------------------------------------------
    # 5. OPUS audit trail
    # ------------------------------------------------------------------
    def check_opus(self) -> None:
        trail = AU.opus_audit(self.main.opus)
        drill = self._read_json(self.art / "ledgers" / "_floor_drill.json")
        statuses = set(trail["by_status"])
        needed = {"accepted", "rejected", "deferred"}

        # The fourth outcome, protected-floor override, is demonstrated by the
        # controlled drill rather than the main run -- see floor_drill.py for
        # why, and note that the drill's decisions carry a distinct proxy
        # version so they can never be mistaken for real ones.
        override_shown = (bool(drill) and drill.get("floor_was_necessary")
                          and drill.get("protected", {}).get("n_floor_overrides", 0) > 0)
        ok = (trail["ok"] and needed.issubset(statuses)
              and trail["n_deferred"] > 0 and override_shown)

        self.add(
            "opus_audit_trail", "OPUS audit trail", ok,
            "read every decision record from the OPUS ledger and confirmed "
            "each candidate carries a status, a proxy score measured from the "
            "live model, and a reason; checked that deferred candidates are "
            "re-offered rather than lost; confirmed the protected-floor "
            "override fires in the controlled drill where the proxy is the "
            "English-tuned kind Session 5 warns about",
            ["ledgers/opus_main.jsonl", "ledgers/_floor_drill.json"],
            n_decisions=trail["n_decisions"],
            by_status=trail["by_status"],
            rejection_reasons=trail["rejection_reasons"],
            n_floor_overrides_main_run=trail["n_floor_overrides"],
            floor_override_demonstrated_in_drill=override_shown,
            drill_unprotected_native_indic=drill.get("unprotected", {}).get(
                "native_indic_sequences"),
            drill_protected_native_indic=drill.get("protected", {}).get(
                "native_indic_sequences"),
            drill_n_overrides=drill.get("protected", {}).get("n_floor_overrides"),
            drill_proxy_version=drill.get("proxy_version"),
            n_deferred=trail["n_deferred"],
            n_deferred_returned=trail["n_deferred_returned"],
            every_candidate_has_a_decision=trail["every_candidate_has_a_decision"],
            by_lane=trail["by_lane"])

    # ------------------------------------------------------------------
    # 6. Crash recovery
    # ------------------------------------------------------------------
    def check_resume(self) -> None:
        before, after, rb = AU.split_at_rollback(self.main.consumption)
        ckpts = sorted((self.art / "checkpoints").glob(f"ckpt-{C.MAIN_BRANCH}-*.json"))
        crash_events = [e for e in self.main.consumption.all_events()
                        if e["type"] == "crash"]

        expected = rb["to_offset"] if rb else 0
        # The step the checkpoint said was next.
        resume_ckpt = None
        for p in ckpts:
            with open(p, "r", encoding="utf-8") as fh:
                rec = json.load(fh)
            if rb and rec["ledger_offset"] == rb["to_offset"]:
                resume_ckpt = rec
        expected_next_step = resume_ckpt["global_step"] if resume_ckpt else -1

        ver = AU.resume_verification(before, after, expected_next_step)
        chain = self.main.consumption.verify_chain()
        binding_ok = bool(resume_ckpt) and (
            self.main.consumption.hash_at(resume_ckpt["ledger_offset"])
            == resume_ckpt["ledger_head_hash"])

        ok = (ver["ok"] and bool(crash_events) and chain["ok"] and binding_ok
              and rb is not None)
        self.add(
            "crash_recovery", "Crash recovery", ok,
            "split the ledger at the rollback marker, compared the batch "
            "content hash the crashed process recorded at each step against "
            "the one the resumed process produced, and confirmed the first "
            "resumed step is exactly the step the checkpoint named -- no skip, "
            "no repeat; re-verified the checkpoint's ledger-head binding",
            ["ledgers/consumption_main.jsonl", "checkpoints/*.json", "run.log"],
            crash_recorded=bool(crash_events),
            crash_exit_code=crash_events[0]["exit_code"] if crash_events else None,
            crash_at_step=crash_events[0]["global_step"] if crash_events else None,
            rollback_recorded=rb is not None,
            rollback_to_offset=expected,
            orphaned_steps=rb["orphaned_steps"] if rb else [],
            expected_next_step=ver["expected_next_step"],
            actual_next_step=ver["actual_next_step"],
            next_batch_matched=ver["next_batch_matched"],
            n_steps_compared=ver["n_steps_compared"],
            n_hash_mismatches=ver["n_hash_mismatches"],
            skipped_steps=ver["skipped_steps"],
            repeated_steps=ver["repeated_steps"],
            checkpoint_ledger_binding_verified=binding_ok,
            ledger_chain_intact=chain["ok"],
            comparisons=ver["comparisons"][:12])

    # ------------------------------------------------------------------
    # 7. Replay and fork
    # ------------------------------------------------------------------
    def check_replay(self) -> None:
        lo, hi = self.profile["replay_interval"]
        rep = AU.replay_interval(self.cat, self.main.consumption, lo, hi,
                                 self.profile["seq_len"])
        fork = AU.fork_verification(self.main.consumption, self.fork.consumption,
                                    self.profile["fork_from_step"])
        ok = rep["ok"] and fork["ok"]
        self.add(
            "replay", "Replay and fork", ok,
            "re-opened the immutable shards, re-cut every recorded token span, "
            "rebuilt each window from its ledger coordinates and compared the "
            "batch id, loss-mask hash and full content hash against the "
            "original; separately confirmed the fork recorded its divergence "
            "point and produced a genuinely different stream",
            ["ledgers/consumption_main.jsonl", "ledgers/consumption_" + C.FORK_BRANCH + ".jsonl"],
            replay_interval=[lo, hi],
            n_microbatches_replayed=rep["n_microbatches_replayed"],
            n_token_spans_verified=rep["n_token_spans_verified"],
            n_replay_mismatches=rep["n_mismatches"],
            replay_mismatches=rep["mismatches"][:5],
            fork_branch=fork.get("fork_branch"),
            fork_parent_step=fork.get("parent_step"),
            fork_divergence_recorded=fork.get("divergence_recorded"),
            fork_shared_steps=fork.get("n_shared_steps"),
            fork_diverging_steps=fork.get("n_diverging_steps"))

    # ------------------------------------------------------------------
    # 8. Learning trace
    # ------------------------------------------------------------------
    def check_learning(self) -> None:
        exposures = self.main.learning.events("shard_exposure")
        traces = self.main.token_trace.events("token_trace")
        n_tokens = sum(t["n_records"] for t in traces)

        with_probe = [e for e in exposures if e.get("probe_loss_delta") is not None]
        linked = all(e.get("shard_id") and e.get("lane") for e in exposures)
        classified = {e.get("usefulness_so_far") for e in exposures}

        token_linked = 0
        for t in traces:
            for r in t["records"]:
                if r.get("shard_id") and r.get("document_id") and r.get("perplexity"):
                    token_linked += 1

        ok = (bool(exposures) and linked and bool(with_probe) and bool(traces)
              and token_linked == n_tokens and n_tokens > 0)
        self.add(
            "learning_trace", "Learning trace", ok,
            "confirmed every shard exposure in the learning ledger carries a "
            "measured probe loss before and after the optimizer step, linked "
            "to the shard and lane it came from, and that every token-level "
            "record carries its own cross-entropy and perplexity linked back "
            "to a source document and shard",
            ["ledgers/learning_main.jsonl", "ledgers/token_trace_main.jsonl"],
            n_shard_exposures=len(exposures),
            n_exposures_with_probe_delta=len(with_probe),
            n_token_trace_batches=len(traces),
            n_token_records=n_tokens,
            n_token_records_linked_to_source=token_linked,
            usefulness_classes=sorted(x for x in classified if x),
            all_exposures_linked_to_shard=linked)

    # ------------------------------------------------------------------
    # 9. Throughput
    # ------------------------------------------------------------------
    def check_throughput(self) -> None:
        perf = self.performance
        counts = perf.get("counts", {})
        thr = perf.get("throughput", {})
        eff = perf.get("efficiency", {})
        wall = perf.get("wall_clock_s", 0.0)

        # Reconstruct the headline rates from the raw counts in the same file.
        recon = {}
        tol_ok = True
        if wall:
            for rate_key, count_key in [
                ("raw_tokens_per_s", "token_positions"),
                ("real_tokens_per_s", "real_tokens"),
                ("useful_loss_bearing_tokens_per_s", "loss_bearing_tokens"),
                ("accepted_loss_bearing_tokens_per_s", "accepted_loss_bearing_tokens"),
            ]:
                want = counts.get(count_key, 0) / wall
                got = thr.get(rate_key, 0.0)
                recon[rate_key] = dict(reported=got, recomputed=round(want, 3),
                                       ok=abs(want - got) < max(0.01, 0.001 * want))
                tol_ok = tol_ok and recon[rate_key]["ok"]

        # Packing utilization must agree with what the ledger actually holds.
        led_real = led_pos = 0
        for ev in self.main.consumption.events("optimizer_step"):
            led_real += ev.get("n_real_tokens", 0)
            led_pos += ev.get("n_positions", 0)
        ledger_util = led_real / led_pos if led_pos else 0.0
        util_ok = abs(ledger_util - eff.get("packing_utilization", -1)) < 0.02

        ok = bool(perf) and tol_ok and util_ok and wall > 0
        self.add(
            "throughput", "Throughput and packing efficiency", ok,
            "re-divided the raw counters in performance.json to reproduce "
            "every headline rate, and cross-checked the reported packing "
            "utilization against the token counts independently recorded in "
            "the consumption ledger",
            ["performance.json", "ledgers/consumption_main.jsonl"],
            wall_clock_s=wall,
            rates_reconstructible=tol_ok,
            reconstruction=recon,
            reported_packing_utilization=eff.get("packing_utilization"),
            packing_utilization_from_ledger=round(ledger_util, 6),
            utilization_agrees=util_ok,
            useful_tokens_per_s=thr.get("useful_loss_bearing_tokens_per_s"),
            raw_tokens_per_s=thr.get("raw_tokens_per_s"),
            padding_waste=eff.get("padding_waste"),
            context_only_fraction=eff.get("context_only_fraction"),
            opus_acceptance_rate=eff.get("opus_acceptance_rate"),
            shard_cache_hit_rate=eff.get("shard_cache_hit_rate"))

    # ------------------------------------------------------------------
    # 10. Shards, manifests and immutability
    # ------------------------------------------------------------------
    def check_shards(self) -> None:
        from . import shards as SH
        bad = []
        for shard_id, man in self.cat.manifests.items():
            shard = self.cat.shards[shard_id]
            if not SH.verify(shard, man["content_hash"]):
                bad.append(shard_id)

        required = set(C.REQUIRED_MANIFEST_FIELDS)
        incomplete = [sid for sid, m in self.cat.manifests.items()
                      if not required.issubset(m.keys())]
        tamper_marker = [m for m in self.markers
                         if m["name"] == "shard_immutability_enforced"]

        ok = (not bad and not incomplete and bool(self.cat.manifests)
              and bool(tamper_marker) and tamper_marker[0]["result"] == "PASS")
        self.add(
            "shard_integrity", "Shards, manifests and immutability", ok,
            "recomputed each shard's content hash from the bytes on disk and "
            "its index, compared against the manifest, and confirmed every "
            "manifest carries all required fields; the run separately "
            "demonstrated that a mutated shard fails this check",
            ["manifests/*.json", "work/shards/*"],
            n_shards=len(self.cat.manifests),
            n_admitted=len(self.cat.admitted),
            n_blocked=len(self.cat.blocked),
            n_content_hash_failures=len(bad), failing_shards=bad,
            n_incomplete_manifests=len(incomplete),
            required_fields=sorted(required),
            tamper_detection_demonstrated=bool(tamper_marker))

    # ------------------------------------------------------------------
    # 11. End-to-end execution
    # ------------------------------------------------------------------
    def check_end_to_end(self) -> None:
        required_events = [
            "shards_created", "manifests_validated", "eval_shard_blocked",
            "mixture_compiled", "batches_packed", "opus_decisions_recorded",
            "checkpoint_saved", "crash_simulated", "run_resumed",
            "historical_stream_replayed", "branch_forked", "audit_completed",
            "performance_measured",
        ]
        log_text = (self.art / "run.log").read_text(encoding="utf-8")
        missing = [e for e in required_events if e not in log_text]

        failed_markers = [m["name"] for m in self.markers if m["result"] == "FAIL"]
        chains = {**self.main.verify_all(), **{f"fork_{k}": v
                                               for k, v in self.fork.verify_all().items()}}
        chain_ok = all(c["ok"] for c in chains.values())

        steps = self.main.consumption.events("optimizer_step")
        expected_steps = self.profile["total_steps"]
        all_steps = sorted({e["global_step"] for e in steps})
        contiguous = all_steps == list(range(expected_steps))

        ok = (not missing and not failed_markers and chain_ok and contiguous)
        self.add(
            "end_to_end", "End-to-end execution", ok,
            "confirmed run.log contains every required event name, that no "
            "check emitted a FAIL marker, that all ten ledger hash chains "
            "verify from genesis, and that the effective consumption ledger "
            "holds exactly one optimizer step per planned step with no gaps",
            ["run.log", "ledgers/*.jsonl"],
            missing_log_events=missing,
            failed_markers=failed_markers,
            n_markers=len(self.markers),
            ledger_chains_ok=chain_ok,
            ledger_chain_detail={k: v["ok"] for k, v in sorted(chains.items())},
            effective_steps=len(all_steps),
            expected_steps=expected_steps,
            steps_contiguous=contiguous)

    # ------------------------------------------------------------------
    def build(self) -> dict:
        self.check_tokenizer()
        self.check_shards()
        self.check_firewall()
        self.check_packing()
        self.check_mixture()
        self.check_opus()
        self.check_learning()
        self.check_resume()
        self.check_replay()
        self.check_throughput()
        self.check_end_to_end()

        n_pass = sum(1 for r in self.rows if r.result == "PASS")
        return dict(
            run_id=C.RUN_ID,
            profile=self.profile_name,
            generated_by="erav6.evidence.EvidenceBuilder",
            generated_from=["run.log", "manifests/", "ledgers/", "checkpoints/",
                            "performance.json", "tokenizer/tokenizer.json",
                            "work/shards/"],
            note=("Every row below is recomputed in this process from the files "
                  "listed in `evidence_paths`. No value is copied from the "
                  "training run's memory; this module never imports the trainer."),
            summary=dict(total=len(self.rows), passed=n_pass,
                         failed=len(self.rows) - n_pass,
                         all_passed=n_pass == len(self.rows)),
            markers_in_run_log=self.markers,
            requirements=[r.as_dict() for r in self.rows],
        )


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------
_HEADLINE = {
    "tokenizer_integrity": "Manifest record",
    "shard_integrity": "Manifest + recomputed content hash",
    "evaluation_firewall": "Blocked-shard event",
    "packing_correctness": "Packed-batch report",
    "mixture_compliance": "Planned versus actual shares",
    "opus_audit_trail": "Candidate decision records",
    "crash_recovery": "Expected and resumed batch ids",
    "replay": "Original and replay hashes",
    "learning_trace": "Loss linked to source data",
    "throughput": "Performance report",
    "end_to_end": "Execution log",
}


def render_markdown(bundle: dict) -> str:
    s = bundle["summary"]
    lines = [
        "# Evidence — ERA V5 Session 6 Training Data Execution System",
        "",
        f"**{s['passed']} / {s['total']} requirements pass.** "
        f"Run `{C.RUN_ID}`, profile `{bundle['profile']}`.",
        "",
        "Every row is recomputed by `src/erav6/evidence.py` from the generated "
        "artefacts, in a separate process that never imports the trainer. "
        "The `Evidence` column names the files the result was derived from.",
        "",
        "| Requirement | Result | Evidence | Key numbers |",
        "|---|---|---|---|",
    ]
    for r in bundle["requirements"]:
        key = r["key"]
        badge = "**PASS**" if r["result"] == "PASS" else "**FAIL**"
        ev = _HEADLINE.get(key, ", ".join(r["evidence"][:1]))
        lines.append(f"| {r['requirement']} | {badge} | {ev} | {_key_numbers(r)} |")

    lines += ["", "---", "", "## How each result was derived", ""]
    for r in bundle["requirements"]:
        lines += [f"### {r['requirement']} — {r['result']}", "",
                  r["how_checked"] + ".", "",
                  "Files read: " + ", ".join(f"`{p}`" for p in r["evidence"]), ""]
        detail = r["detail"]
        keys = [k for k in detail if not isinstance(detail[k], (list, dict))][:10]
        if keys:
            lines.append("| Field | Value |")
            lines.append("|---|---|")
            for k in keys:
                lines.append(f"| `{k}` | {detail[k]} |")
            lines.append("")

    lines += ["---", "",
              "## Execution log markers", "",
              "| Marker | Result | Phase |", "|---|---|---|"]
    for m in bundle["markers_in_run_log"]:
        lines.append(f"| `{m['name']}` | {m['result']} | {m.get('phase', '-')} |")
    lines.append("")
    return "\n".join(lines)


def _key_numbers(row: dict) -> str:
    d = row["detail"]
    picks = {
        "tokenizer_integrity": ["n_manifests_checked", "n_mismatched"],
        "shard_integrity": ["n_shards", "n_admitted", "n_blocked", "n_content_hash_failures"],
        "evaluation_firewall": ["n_blocked_shards", "n_distinct_shards_consumed"],
        "packing_correctness": ["n_sequences_rebuilt", "n_violations",
                                "overall_packing_utilization"],
        "mixture_compliance": ["max_abs_unexplained_drift", "max_abs_drift_vs_planned",
                               "total_sequences_substituted", "floor_violations"],
        "opus_audit_trail": ["n_decisions", "n_deferred", "drill_n_overrides",
                             "floor_override_demonstrated_in_drill"],
        "crash_recovery": ["expected_next_step", "actual_next_step", "n_hash_mismatches"],
        "replay": ["n_microbatches_replayed", "n_token_spans_verified",
                   "n_replay_mismatches"],
        "learning_trace": ["n_shard_exposures", "n_token_records"],
        "throughput": ["useful_tokens_per_s", "rates_reconstructible"],
        "end_to_end": ["effective_steps", "n_markers", "ledger_chains_ok"],
    }.get(row["key"], [])
    bits = [f"{k}={d[k]}" for k in picks if k in d]
    return ", ".join(f"`{b}`" for b in bits)


def generate(artifacts: Path | str = None,
             profile_name: str = C.DEFAULT_PROFILE) -> dict:
    art = Path(artifacts or C.ARTIFACTS)
    bundle = EvidenceBuilder(art, profile_name).build()
    with open(art / "evidence.json", "w", encoding="utf-8", newline="\n") as fh:
        json.dump(bundle, fh, indent=2, sort_keys=True)
        fh.write("\n")
    with open(art / "evidence.md", "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_markdown(bundle))
        fh.write("\n")
    return bundle
